### ISSUE TITLE
Add human readable event types and reasons to MQTT event message

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-mqtt#2]
cf. https://github.com/uhppoted/uhppoted/discussions/12

Include human readable descriptions corresponding to the event type and event reason codes in the MQTT event message.

Requirements:
1. Event message structure should be backwards compatible
2. Messages must be internationalisable

**Comment by YBonline** [comment]
Can you also describe how the you are supposed to call the door open event? It seems to require a card number, but that card number doesn't seem to be verified from the board, but instead perhaps a config file? I haven't quite figured out what that format is when I have multiple controllers. (I temporarily worked around the issue by commenting out the card number validation and that works fine and just shows as a normal "remote door open" event) Thanks again!

**Comment by uhppoted** [comment]
Hi,

I've added the first draft of a write-up for `open-door` [here](https://github.com/uhppoted/uhppoted-mqtt/blob/master/documentation/messages.md#open-door) - but basically you need to have an MQTT `cards` file that authorises the card (because remote open door is a typically a supervisor function) and the card also needs to be a valid card on the controller i.e. have valid start and end dates and also permission for the door (it can be a virtual card i.e. not a real swipable card).

The reason for the additional complication is that _uhppoted-mqtt_ was originally intended to also support card-less access by e.g. a mobile phone app which of course bypasses all the security provided by a physical token.

**Comment by twystd** [comment]
Added support for internationalisable event type, direction and reason text descriptions. 

### Notes
1. The `event` _struct_ has changed to accommodate the additional fields. Setting the _mqtt.protocol.version_ field in the _uhppoted.conf_ file to `v0` will revert the changes to base `event` struct.
2. Translations default to the _en_ locale but can be customised by setting the _mqtt.translation.locale_ configuration key to a JSON file that contains the desired locations.

Pending release.

**Comment by uhppoted** [comment]
Fixed in [release v0.8.1](https://github.com/uhppoted/uhppoted-mqtt/releases/tag/v0.8.1)
