### ISSUE TITLE
Investigate possible bug in system monitor

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-mqtt#5]
> Good news !
> Change the listener address in uhppoted.conf to [0.0.0.0:60001](http://0.0.0.0:60001/) corrected heath-check
> Change the watchdog interval in uhppoted.conf to 30s corrected watchdog

Notes:
1. The watchdog interval is probably related to a hardcoded 60s interval in the watchdog implementation
2. The listener address thing is possibly related to [Fix health-check listener monitor to accommodate the default 0.0.0.0 address](https://github.com/uhppoted/uhppoted-lib/issues/2)

Ref. https://github.com/uhppoted/uhppoted/discussions/14

**Comment by twystd** [comment]
1. _listener address_ is fixed by https://github.com/uhppoted/uhppoted-lib/issues/2
2. Reworked _uhppoted-lib_ `watchdog` logic to account for _health-check interval_

Pending release.

**Comment by uhppoted** [comment]
Closing - released in [v0.8.2](https://github.com/uhppoted/uhppoted-mqtt/releases/tag/v0.8.2)
